apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 12
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
      - id: 1
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
      - id: 2
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
      - id: 3
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
      - id: 4
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
      - id: 5
        type: persistent-claim
        size: 200Gi
        deleteClaim: true
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    rack:
      topologyKey: topology.kubernetes.io/region
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}